// ============================================================
// Seed data – historické zakázky AmperSun
// Slouží jako základ pro doporučení cen
// ============================================================

import { HistorickaZakazka, Kalkulace } from './types';

export const HISTORICKE_ZAKAZKY: HistorickaZakazka[] = [
  {
    id: 'hz-001',
    typZakazky: 'fve_rodinny_dum',
    lokalita: 'Brno',
    kraj: 'Jihomoravský',
    vykonFVE: 6.6,
    pocetPanelu: 15,
    baterieAno: false,
    kapacitaBaterie: 0,
    typObjektu: 'rodinny_dum',
    typStrechy: 'sediova',
    slozitostMontaze: 'jednoducha',
    doporucenaCena: 285000,
    finalniCena: 275000,
    datumRealizace: '2024-03-15',
    vzdalenostRealizace: 12,
    wallboxAno: false,
    vyrizeniDotaceAno: true,
  },
  {
    id: 'hz-002',
    typZakazky: 'fve_rodinny_dum',
    lokalita: 'Znojmo',
    kraj: 'Jihomoravský',
    vykonFVE: 8.8,
    pocetPanelu: 20,
    baterieAno: true,
    kapacitaBaterie: 10,
    typObjektu: 'rodinny_dum',
    typStrechy: 'sediova',
    slozitostMontaze: 'jednoducha',
    doporucenaCena: 420000,
    finalniCena: 415000,
    datumRealizace: '2024-04-20',
    vzdalenostRealizace: 65,
    wallboxAno: true,
    vyrizeniDotaceAno: true,
  },
  {
    id: 'hz-003',
    typZakazky: 'fve_rodinny_dum',
    lokalita: 'Hodonín',
    kraj: 'Jihomoravský',
    vykonFVE: 10,
    pocetPanelu: 22,
    baterieAno: true,
    kapacitaBaterie: 15,
    typObjektu: 'rodinny_dum',
    typStrechy: 'valbova',
    slozitostMontaze: 'stredni',
    doporucenaCena: 498000,
    finalniCena: 490000,
    datumRealizace: '2024-05-10',
    vzdalenostRealizace: 80,
    wallboxAno: false,
    vyrizeniDotaceAno: true,
  },
  {
    id: 'hz-004',
    typZakazky: 'fve_rodinny_dum',
    lokalita: 'Olomouc',
    kraj: 'Olomoucký',
    vykonFVE: 7.4,
    pocetPanelu: 17,
    baterieAno: false,
    kapacitaBaterie: 0,
    typObjektu: 'rodinny_dum',
    typStrechy: 'pultova',
    slozitostMontaze: 'jednoducha',
    doporucenaCena: 315000,
    finalniCena: 305000,
    datumRealizace: '2024-06-05',
    vzdalenostRealizace: 110,
    wallboxAno: false,
    vyrizeniDotaceAno: false,
  },
  {
    id: 'hz-005',
    typZakazky: 'fve_rodinny_dum',
    lokalita: 'Třebíč',
    kraj: 'Vysočina',
    vykonFVE: 12.1,
    pocetPanelu: 28,
    baterieAno: true,
    kapacitaBaterie: 20,
    typObjektu: 'rodinny_dum',
    typStrechy: 'sediova',
    slozitostMontaze: 'slozita',
    doporucenaCena: 620000,
    finalniCena: 598000,
    datumRealizace: '2024-07-18',
    vzdalenostRealizace: 45,
    wallboxAno: true,
    vyrizeniDotaceAno: true,
  },
  {
    id: 'hz-006',
    typZakazky: 'fve_firma',
    lokalita: 'Brno',
    kraj: 'Jihomoravský',
    vykonFVE: 50,
    pocetPanelu: 110,
    baterieAno: false,
    kapacitaBaterie: 0,
    typObjektu: 'prumyslovy_objekt',
    typStrechy: 'ploche',
    slozitostMontaze: 'stredni',
    doporucenaCena: 1850000,
    finalniCena: 1780000,
    datumRealizace: '2023-11-20',
    vzdalenostRealizace: 8,
    wallboxAno: false,
    vyrizeniDotaceAno: false,
  },
  {
    id: 'hz-007',
    typZakazky: 'fve_firma',
    lokalita: 'Ostrava',
    kraj: 'Moravskoslezský',
    vykonFVE: 100,
    pocetPanelu: 220,
    baterieAno: true,
    kapacitaBaterie: 100,
    typObjektu: 'prumyslovy_objekt',
    typStrechy: 'ploche',
    slozitostMontaze: 'stredni',
    doporucenaCena: 4200000,
    finalniCena: 4050000,
    datumRealizace: '2024-01-15',
    vzdalenostRealizace: 170,
    wallboxAno: false,
    vyrizeniDotaceAno: false,
  },
  {
    id: 'hz-008',
    typZakazky: 'fve_firma',
    lokalita: 'Přerov',
    kraj: 'Olomoucký',
    vykonFVE: 30,
    pocetPanelu: 66,
    baterieAno: false,
    kapacitaBaterie: 0,
    typObjektu: 'kancelarske_prostory',
    typStrechy: 'ploche',
    slozitostMontaze: 'jednoducha',
    doporucenaCena: 1150000,
    finalniCena: 1120000,
    datumRealizace: '2024-02-28',
    vzdalenostRealizace: 95,
    wallboxAno: true,
    vyrizeniDotaceAno: false,
  },
  {
    id: 'hz-009',
    typZakazky: 'fve_obec',
    lokalita: 'Kroměříž',
    kraj: 'Zlínský',
    vykonFVE: 25,
    pocetPanelu: 56,
    baterieAno: true,
    kapacitaBaterie: 50,
    typObjektu: 'obecni_objekt',
    typStrechy: 'sediova',
    slozitostMontaze: 'stredni',
    doporucenaCena: 1320000,
    finalniCena: 1280000,
    datumRealizace: '2024-03-10',
    vzdalenostRealizace: 75,
    wallboxAno: false,
    vyrizeniDotaceAno: true,
  },
  {
    id: 'hz-010',
    typZakazky: 'fve_obec',
    lokalita: 'Uherské Hradiště',
    kraj: 'Zlínský',
    vykonFVE: 40,
    pocetPanelu: 90,
    baterieAno: false,
    kapacitaBaterie: 0,
    typObjektu: 'obecni_objekt',
    typStrechy: 'ploche',
    slozitostMontaze: 'jednoducha',
    doporucenaCena: 1580000,
    finalniCena: 1550000,
    datumRealizace: '2024-04-05',
    vzdalenostRealizace: 90,
    wallboxAno: false,
    vyrizeniDotaceAno: true,
  },
  {
    id: 'hz-011',
    typZakazky: 'bateriove_uloziste',
    lokalita: 'Brno',
    kraj: 'Jihomoravský',
    vykonFVE: 0,
    pocetPanelu: 0,
    baterieAno: true,
    kapacitaBaterie: 10,
    typObjektu: 'rodinny_dum',
    typStrechy: 'sediova',
    slozitostMontaze: 'jednoducha',
    doporucenaCena: 185000,
    finalniCena: 178000,
    datumRealizace: '2024-05-22',
    vzdalenostRealizace: 15,
    wallboxAno: false,
    vyrizeniDotaceAno: false,
  },
  {
    id: 'hz-012',
    typZakazky: 'bateriove_uloziste',
    lokalita: 'Zlín',
    kraj: 'Zlínský',
    vykonFVE: 0,
    pocetPanelu: 0,
    baterieAno: true,
    kapacitaBaterie: 20,
    typObjektu: 'rodinny_dum',
    typStrechy: 'sediova',
    slozitostMontaze: 'stredni',
    doporucenaCena: 340000,
    finalniCena: 325000,
    datumRealizace: '2024-06-18',
    vzdalenostRealizace: 120,
    wallboxAno: false,
    vyrizeniDotaceAno: false,
  },
  {
    id: 'hz-013',
    typZakazky: 'servis_rozsireni',
    lokalita: 'Brno',
    kraj: 'Jihomoravský',
    vykonFVE: 3.3,
    pocetPanelu: 8,
    baterieAno: false,
    kapacitaBaterie: 0,
    typObjektu: 'rodinny_dum',
    typStrechy: 'sediova',
    slozitostMontaze: 'jednoducha',
    doporucenaCena: 145000,
    finalniCena: 138000,
    datumRealizace: '2024-07-05',
    vzdalenostRealizace: 20,
    wallboxAno: false,
    vyrizeniDotaceAno: false,
  },
  {
    id: 'hz-014',
    typZakazky: 'fve_rodinny_dum',
    lokalita: 'Vyškov',
    kraj: 'Jihomoravský',
    vykonFVE: 9.24,
    pocetPanelu: 21,
    baterieAno: true,
    kapacitaBaterie: 12,
    typObjektu: 'rodinny_dum',
    typStrechy: 'sediova',
    slozitostMontaze: 'stredni',
    doporucenaCena: 460000,
    finalniCena: 445000,
    datumRealizace: '2024-08-12',
    vzdalenostRealizace: 30,
    wallboxAno: true,
    vyrizeniDotaceAno: true,
  },
  {
    id: 'hz-015',
    typZakazky: 'fve_firma',
    lokalita: 'Hodonín',
    kraj: 'Jihomoravský',
    vykonFVE: 75,
    pocetPanelu: 165,
    baterieAno: true,
    kapacitaBaterie: 75,
    typObjektu: 'zemedelsky_objekt',
    typStrechy: 'pultova',
    slozitostMontaze: 'slozita',
    doporucenaCena: 3250000,
    finalniCena: 3100000,
    datumRealizace: '2024-09-01',
    vzdalenostRealizace: 78,
    wallboxAno: false,
    vyrizeniDotaceAno: false,
  },
];

// Ukázkové existující kalkulace (pro demonstraci v seznamu)
export const DEMO_KALKULACE: Kalkulace[] = [
  {
    id: 'kal-001',
    cisloNabidky: 'AMP-2024-001',
    datumVytvoreni: '2024-10-01T09:30:00',
    datumUpravy: '2024-10-05T14:20:00',
    typZakazky: 'fve_rodinny_dum',
    klient: {
      jmeno: 'Petr Novák',
      kontaktniOsoba: 'Petr Novák',
      telefon: '+420 605 123 456',
      email: 'petr.novak@email.cz',
      adresaRealizace: 'Lipová 12, 602 00 Brno',
      fakturacniAdresa: 'Lipová 12, 602 00 Brno',
      poznamka: 'Zákazník má zájem o dotaci NZU.',
    },
    technickeUdaje: {
      spotrebaElektriny: 5500,
      vykonFVE: 8.8,
      pocetPanelu: 20,
      typPanelu: 'Longi Solar Hi-MO 440W',
      typStridace: 'Fronius Primo 8.2',
      baterieAno: true,
      kapacitaBaterie: 10,
      wallboxAno: true,
      chyteRizeniAno: true,
      zalozniRezimAno: false,
      monitoringAno: true,
      typObjektu: 'rodinny_dum',
      typStrechy: 'sediova',
      sklonStrechy: 35,
      orientaceStrechy: 'jih',
      slozitostMontaze: 'jednoducha',
      vzdalenostRealizace: 15,
      elektroupravyAno: false,
      revizeAno: true,
      projektovaDokumentaceAno: false,
      vyrizeniDotaceAno: true,
    },
    obchodniUdaje: {
      interniPoznamka: 'Zákazník oslovil přes doporučení.',
      priorita: 'vysoka',
      predpokladanyTermin: '2024-12-01',
      stav: 'nabidka_odeslana',
    },
    cenova: {
      polozky: [],
      celkemBezDPH: 372727,
      dphSazba: 21,
      dphCastka: 78273,
      celkemSDPH: 451000,
      odhadNakladu: 310000,
      odhadMarze: 62727,
      odhadMarzeProc: 16.8,
      pravidlovaKalkulace: 451000,
      doporucenaCena: 445000,
      cenoveRozpeti: { min: 415000, max: 490000 },
      podobneZakazky: [],
      finalniCena: 451000,
      sleva: 0,
      slevaProc: 0,
      duvodZmeny: '',
      datumSchvaleni: '2024-10-05T14:20:00',
      schvaleno: true,
    },
  },
  {
    id: 'kal-002',
    cisloNabidky: 'AMP-2024-002',
    datumVytvoreni: '2024-10-15T11:00:00',
    datumUpravy: '2024-10-15T11:00:00',
    typZakazky: 'fve_firma',
    klient: {
      jmeno: 'AGRO Morava s.r.o.',
      kontaktniOsoba: 'Ing. Jana Horáková',
      telefon: '+420 723 456 789',
      email: 'horakova@agromoava.cz',
      adresaRealizace: 'Průmyslová 5, 695 01 Hodonín',
      fakturacniAdresa: 'Průmyslová 5, 695 01 Hodonín',
      poznamka: '',
    },
    technickeUdaje: {
      spotrebaElektriny: 85000,
      vykonFVE: 50,
      pocetPanelu: 112,
      typPanelu: 'Longi Solar Hi-MO 450W',
      typStridace: 'SMA Sunny Tripower 50',
      baterieAno: false,
      kapacitaBaterie: 0,
      wallboxAno: false,
      chyteRizeniAno: true,
      zalozniRezimAno: false,
      monitoringAno: true,
      typObjektu: 'prumyslovy_objekt',
      typStrechy: 'ploche',
      sklonStrechy: 10,
      orientaceStrechy: 'jih',
      slozitostMontaze: 'stredni',
      vzdalenostRealizace: 78,
      elektroupravyAno: true,
      revizeAno: true,
      projektovaDokumentaceAno: true,
      vyrizeniDotaceAno: false,
    },
    obchodniUdaje: {
      interniPoznamka: 'Velká zakázka, možnost dalšího rozšíření.',
      priorita: 'vysoka',
      predpokladanyTermin: '2025-02-01',
      stav: 'ceka_na_schvaleni',
    },
    cenova: null,
  },
  {
    id: 'kal-003',
    cisloNabidky: 'AMP-2024-003',
    datumVytvoreni: '2024-11-02T08:45:00',
    datumUpravy: '2024-11-10T16:30:00',
    typZakazky: 'bateriove_uloziste',
    klient: {
      jmeno: 'Marie Svobodová',
      kontaktniOsoba: 'Marie Svobodová',
      telefon: '+420 777 890 123',
      email: 'svobodova.marie@seznam.cz',
      adresaRealizace: 'Zahradní 8, 760 01 Zlín',
      fakturacniAdresa: 'Zahradní 8, 760 01 Zlín',
      poznamka: 'Dokoupení k existující FVE.',
    },
    technickeUdaje: {
      spotrebaElektriny: 4200,
      vykonFVE: 0,
      pocetPanelu: 0,
      typPanelu: '-',
      typStridace: 'stávající Fronius',
      baterieAno: true,
      kapacitaBaterie: 10,
      wallboxAno: false,
      chyteRizeniAno: false,
      zalozniRezimAno: false,
      monitoringAno: false,
      typObjektu: 'rodinny_dum',
      typStrechy: 'sediova',
      sklonStrechy: 30,
      orientaceStrechy: 'jihozapad',
      slozitostMontaze: 'jednoducha',
      vzdalenostRealizace: 120,
      elektroupravyAno: false,
      revizeAno: false,
      projektovaDokumentaceAno: false,
      vyrizeniDotaceAno: false,
    },
    obchodniUdaje: {
      interniPoznamka: '',
      priorita: 'stredni',
      predpokladanyTermin: '2024-12-15',
      stav: 'schvaleno',
    },
    cenova: {
      polozky: [],
      celkemBezDPH: 151240,
      dphSazba: 21,
      dphCastka: 31760,
      celkemSDPH: 183000,
      odhadNakladu: 130000,
      odhadMarze: 21240,
      odhadMarzeProc: 14.0,
      pravidlovaKalkulace: 183000,
      doporucenaCena: 178000,
      cenoveRozpeti: { min: 165000, max: 200000 },
      podobneZakazky: [],
      finalniCena: 183000,
      sleva: 0,
      slevaProc: 0,
      duvodZmeny: '',
      datumSchvaleni: '2024-11-10T16:30:00',
      schvaleno: true,
    },
  },
  {
    id: 'kal-004',
    cisloNabidky: 'AMP-2024-004',
    datumVytvoreni: '2024-11-20T13:15:00',
    datumUpravy: '2024-11-20T13:15:00',
    typZakazky: 'fve_rodinny_dum',
    klient: {
      jmeno: 'Tomáš Kratochvíl',
      kontaktniOsoba: 'Tomáš Kratochvíl',
      telefon: '+420 601 234 567',
      email: 'kratochvil.t@gmail.com',
      adresaRealizace: 'Slunečná 3, 796 01 Prostějov',
      fakturacniAdresa: 'Slunečná 3, 796 01 Prostějov',
      poznamka: '',
    },
    technickeUdaje: {
      spotrebaElektriny: 6800,
      vykonFVE: 11,
      pocetPanelu: 24,
      typPanelu: 'Jinko Solar Tiger Neo 460W',
      typStridace: 'Huawei SUN2000 10KTL',
      baterieAno: true,
      kapacitaBaterie: 15,
      wallboxAno: true,
      chyteRizeniAno: true,
      zalozniRezimAno: true,
      monitoringAno: true,
      typObjektu: 'rodinny_dum',
      typStrechy: 'valbova',
      sklonStrechy: 40,
      orientaceStrechy: 'jihozapad',
      slozitostMontaze: 'stredni',
      vzdalenostRealizace: 60,
      elektroupravyAno: true,
      revizeAno: true,
      projektovaDokumentaceAno: false,
      vyrizeniDotaceAno: true,
    },
    obchodniUdaje: {
      interniPoznamka: 'Zákazník chce záložní režim.',
      priorita: 'stredni',
      predpokladanyTermin: '2025-03-01',
      stav: 'rozpracovano',
    },
    cenova: null,
  },
];
